# Generated by Django 5.0.6 on 2024-06-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('nice_feeling', models.BooleanField(default=False, verbose_name='приятная привычка?')),
                ('periodicity', models.IntegerField(default=7, verbose_name='периодичность выполнения привычки (в днях)')),
                ('last_completed', models.DateField(blank=True, null=True, verbose_name='последний раз')),
                ('is_public', models.BooleanField(default=True, verbose_name='доступно для других?')),
                ('place', models.CharField(max_length=255, verbose_name='место действия')),
                ('duration', models.DurationField(verbose_name='время выполнения привычки')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
